{% set name = "wagtail-autocomplete" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wagtail-autocomplete-{{ version }}.tar.gz
  sha256: b2ba0f5c8a0e43cdc124a9503d91e9815fb0251a1431d52db5868306ab935059

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - wagtail >=2.15

test:
  imports:
    - wagtailautocomplete
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/wagtail/wagtail-autocomplete
  summary: An Autocomplete edit handler for Pages, Snippets, and more.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
